# Generated by Django 4.1.6 on 2023-02-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoStyleApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
