# Generated by Django 4.1.6 on 2023-02-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoStyleApp', '0002_product_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_review',
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
