# Generated by Django 4.1.6 on 2023-02-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neoStyleApp', '0007_customer_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='device',
        ),
    ]
