# Generated by Django 4.1.6 on 2023-02-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoStyleApp', '0009_alter_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=60)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_message', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
