# Generated by Django 4.1.6 on 2023-02-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoStyleApp', '0012_brand_product_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_name', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
