# Generated by Django 4.1.6 on 2023-02-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neoStyleApp', '0016_newsletteruser_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='size_category',
            new_name='size_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_previous_price',
        ),
    ]
